### ISSUE TITLE
To implement AutomatedLinkAcceptanceProxy version 1.0.1 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AutomatedLinkAcceptanceProxy#101]
To completely implement the version 1.0.1 changes , the following tasks and their subtasks needs to be completed.
All the tasks needs to be implemented , tested , reviewed and merged to the develop branch.

### Initial setup and integration of ApplicationPattern :
- [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/82
- [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/83
- [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/84
### Individual Services :
- [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/139

To support the /v1/provide-acceptance-data-of-link-endpoint perform the following tasks, 
- [x] Support the query parameter in the RESTcall to MWDI https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/81
- [x] Read the Ltp structure for the provided mount-name https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/85
- [x]  Find the air-interface uuid under test https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/86
- [x] Formulate the response body for the property “air-interface”
    - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/87
    - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/88
    - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/89
- [x] Formulate the response body for the property “vlan-interface”
    - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/90
    - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/91
- [x] Formulate the response body for the property “inventory”
   - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/92
   - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/93
   - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/94
   - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/95
   - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/96
   - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/97
   - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/98
   - [x] https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/99
- [x] Formulate the parameters for Alarms https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/100

**Comment by PrathibaJee** [comment]
Closing this issue as all the sub tasks are completed.
